### PR TITLE
misc README nits (third try)

### PR DESCRIPTION
**Pull request by davide125**
Redo of #24

### CODE REVIEW

**Comment by jaymzh** [comment]
The import failed, but I've fixed imports now. IN the meantime your tests fail.... I think you need a re-base and a force-push and the import should happen again and your tests should pass.

**Comment by facebook-github-bot-4** [comment]
@davide125 updated the pull request - [view changes](https://github.com/facebook/chef-cookbooks/pull/26/files/ff954078cf9d45a4cfad3baf762df543c1e0b191..d22c23df0724331d2d027151fe1bc34221f8f707) - [changes since last import](https://github.com/facebook/chef-cookbooks/pull/26/files/ff954078cf9d45a4cfad3baf762df543c1e0b191..d22c23df0724331d2d027151fe1bc34221f8f707)

**Comment by facebook-github-bot-9** [comment]
@davide125 updated the pull request - [view changes](https://github.com/facebook/chef-cookbooks/pull/26/files/d22c23df0724331d2d027151fe1bc34221f8f707..47995fedc52c62964d590baebe90f20477ca85ae) - [changes since last import](https://github.com/facebook/chef-cookbooks/pull/26/files/ff954078cf9d45a4cfad3baf762df543c1e0b191..47995fedc52c62964d590baebe90f20477ca85ae)

**Comment by davide125** [comment]
This is failing rubocop on unrelated stuff. I can fix it, but we should double check the rules first as they may need to be synced.

**Pull request closed without merging**
