### PR TITLE
Remove reference to oncalls from public doc

### PR DESCRIPTION
**Pull request by elthariel**
Hi oscore :),

Was just browsing the repo, considering using some of this stuff for my own infra and came accross a reference to the chef oncall, which probably shouldn't be laying around open source code.

Signed-off-by: Julien 'Lta' BALLET <contact@lta.io>

### CODE REVIEW

**Comment by jaymzh** [comment]
It's telling you that because you're an ex-employee and thus the tool can't overwrite the existing CLA with a new one. Which requires sending in a physically signed paper - cla@ can help, but since this is simply 2 line comment change, we'll call it "obvious fix" and merge it.

**Comment by elthariel** [comment]
Yeah, I assumed it was something along those lines, I've send them an email.

Thx

**Comment by jaymzh** [comment]
OK I was an idiot and merged this here instead of telling the bot to do it and it broke things so I had to revert it. I'm going to inquire about if I can make the bot pull in a closed PR, but if you wanna send another PR I'll do it right... and/or I can just make a PR and say @elthariel  was the original author...

**Comment by jaymzh** [comment]
Alright I was able to make a diff that got sync'd as you. We're all good. :)

**Comment by elthariel** [comment]
Haha, shit happens :) but don't worry about it, it's just 2 lines.

**Pull request merged**
