### PR TITLE
Adding new apache cookbook.

### PR DESCRIPTION
**Pull request by jaymzh**
This isn't ready for merge yet - and in fact we'll have to do some
internal juggling first in order to merge this - but I want to get it
out there so that (1) people know I'm working on this (this came from my
work on SCALE stuff) and don't duplicate effort and (2) people can start
using it if they want.

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
@jaymzh updated the pull request - [view changes](https://github.com/facebook/chef-cookbooks/pull/19/files/51ad185baf1c639c383da516043099d08275d905..5742a0f5edfbac5a09359cd4fcc4e0c0fedf8b5e)

**Comment by jaymzh** [comment]
OK we're ready to pull this in and start moving to it. Once tests pass.

**Comment by jaymzh** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-6** [comment]
@jaymzh updated the pull request - [view changes](https://github.com/facebook/chef-cookbooks/pull/19/files/5742a0f5edfbac5a09359cd4fcc4e0c0fedf8b5e..046631bd51554e33a6df86272b7c77af2a718c41) - [changes since last import](https://github.com/facebook/chef-cookbooks/pull/19/files/5742a0f5edfbac5a09359cd4fcc4e0c0fedf8b5e..046631bd51554e33a6df86272b7c77af2a718c41)

**Comment by facebook-github-bot-7** [comment]
@jaymzh updated the pull request - [view changes](https://github.com/facebook/chef-cookbooks/pull/19/files/046631bd51554e33a6df86272b7c77af2a718c41..a9b91f14ede655e1653f049390858b96f4c430a6) - [changes since last import](https://github.com/facebook/chef-cookbooks/pull/19/files/5742a0f5edfbac5a09359cd4fcc4e0c0fedf8b5e..a9b91f14ede655e1653f049390858b96f4c430a6)

**Comment by facebook-github-bot-6** [comment]
@jaymzh updated the pull request - [view changes](https://github.com/facebook/chef-cookbooks/pull/19/files/a9b91f14ede655e1653f049390858b96f4c430a6..0049567cea23fc8393b1a32e5377cb5f92134a65) - [changes since last import](https://github.com/facebook/chef-cookbooks/pull/19/files/5742a0f5edfbac5a09359cd4fcc4e0c0fedf8b5e..0049567cea23fc8393b1a32e5377cb5f92134a65)

**Pull request merged**
