### PR TITLE
New cookbook: fb_profile

### PR DESCRIPTION
**Pull request by jaymzh**
A cookbook to manage global profile files using the FB attribute-driven
model.

### CODE REVIEW

**Comment by davide125** [comment]
Funnily enough, we have an internal `fb_etc_profiled` targeting Fedora that we were about to publish. I'll see if I can get it merged with this one instead, as they look similar enough. cc @michel-slm

**Comment by jaymzh** [comment]
This one is incredibly simple... if yours is better, I'm happy to migrate to it. I just needed something. I was planning on adding an overwrite option to /etc/bash.bashrc which would include a file as well that we could maintain since it lacks such a thing...

**Comment by davide125** [comment]
@jaymzh our internal version is at https://github.com/davide125/chef-cookbooks/tree/fb_etc_profiled/cookbooks/fb_etc_profiled

I'm going to hold off on merging it in this repo, as I'd rather get a unified solution. @michel-slm mentioned one of the requirements for us is that this will need to support OSX.

**Comment by jaymzh** [comment]
Last I checked, OSX had dropped all support for global profile files...?

**Comment by michel-slm** [comment]
Checking with our resident Mac expert on the macOS situation. We do know that we currently run fb_etc_profiled on Macs but if this is going away long-term I'm fine with not adding macOS support

**Comment by jaymzh** [comment]
So I took a look over `fb_etc_profile_d`, to get an idea of which one I think should be merged into which one (I'm always happy to throw mine away if there's a more complete one).

In this case I think we probably want to base it on mine. Here's my thoughts on `fb_etc_profiled`:

1. I wouldn't override `/etc/profile` in the general sense - letting the OS do it's defaults here is probably best. It's a little non-standard for us to not just own an entire file let there be no other file, but in this case this isn't a finite-set of things. More below.
2. Dropping off multiple files in `/etc/profile.d` is pretty anti-fb-model here. The more fb-y thing to do would be to have a single file in there that implements whatever people pass into the API. Its just the same as we don't drop off `/etc/sysctl.conf.d/` files, we just manage `/etc/sysctl.conf` and (though in this case, there's not a full-known-set of things, hence I wouldn't overwrite `/etc/profile` itself). Here's a few specific reasons:
* We then need to clean up those files. This is do-able of course, but why add more work?
* We have to worry about source-ing order. We could, again, do some interesting work-arounds here - hashes in ruby are ordered so you could try to name them in the order you got them, but that leads to really un-fun stuff like "oh someone added a new entry so file after it got renamed!"
* It becomes much more difficult to see what changed in a given run because you have to piece together multiple diffs
(That's why in mine I make a `/etc/profile.d/fb_profile.sh`.)
3. There's no real API here - we're just jamming in entire files into variables via heredocs into the node object. It's hard to introspect, it's hard to code-review, it's hard to indent. Since, ultimately we'll generate a shell script, that functionality is of course necessary, for the common stuff, creating a nice API will help (ala [aliases](https://github.com/facebook/chef-cookbooks/pull/105/files#diff-b49441bfb7e32a6b9f2c9e85af74b4e7R25) and [variables](https://github.com/facebook/chef-cookbooks/pull/105/files#diff-b49441bfb7e32a6b9f2c9e85af74b4e7R33). This leads to some problems like:
* That model loses all the 'cascading' nature of Chef FB attribute model. We have *no* way of knowing who set an aliase for `ll`, nor do I have an easy way of overriding it. I just have to make my own and hope my files is loaded later. It also means, as you currently have it, If I call my "key" `zzz_fuck_everyone`, I win, even if I'm the first cookbook, rather than that runlist-order winning (though of course a later runlist could look for that and change it, but it's no longer using the intuitive order that is common in the FB model).

Now, all that said, mine is missing some useful features too and needs to grow, though I *think* as it stands it can cover for what this does.

Onto the big caveat. I said I would not overwrite `/etc/profile`... and in fact we should really never do that because every single distro's `/etc/profile` sources `/etc/profile.d/*` at the end (which means we probably should cleanup other stuff in that directory and just write our own single file, but that's already covered above, I think). **HOWEVER** I also want to implement the bashrc/zshrc files for non-login shells. When it comes to `/etc/bash.bashrc` (debian/ubuntu) or `/etc/bashrc` (fedora/rhel/centos) only the RH ones have a nice include where they re-source stuff in profile.d when necessary. This is great in that it makes it easy to not have to touch that file on RH-like OSes, but we'll probably *need* to on Debian-like OSes to start managing bashrc/zshrc globally, despite the fact that that's generally ill-advised.

Fortunately the debian/ubuntu `/etc/bash.bashrc` is only 23 lines, and doesn't change much, so overwriting it is... not the most-terribly-heinous thing ever because we can make ours those 23 lines plus the few lines we wanna "steal" from RH. :)

I hope that helps

**Comment by michel-slm** [comment]
Given on macOS we can't rely on /etc/profile being loaded anyway, I'm fine with landing this as it is now, and then we can see internally if we can switch our Mac users to this (and finding a way to consistently load fb_profile.sh).

Right now fb_etc_profile_d only works on a Mac if you do a `bash --login`, not sure how it even works for the person who authored the call site that uses it.

**Pull request closed without merging**
