### PR TITLE
[rspec] bump gems to 3.11

### PR DESCRIPTION
**Pull request by dafyddcrosby**

### CODE REVIEW

**Review by jaymzh — APPROVED** [review]
ok, except tests...

**Review by davide125 — APPROVED** [review]

**Comment by dafyddcrosby** [comment]
> ok, except tests...

Got the tests working in #229 (after bumping the client version to Chef 16)

**Review by jaymzh — APPROVED** [review]
Right. I know the kitchen tests are fucked, so you can ignore those. Rebase this and merge away.

**Comment by dafyddcrosby** [comment]
> Right. I know the kitchen tests are fucked, so you can ignore those. Rebase this and merge away.

Thanks - I want to sort the kitchen tests out before ChefConf if possible, but suspect that might be a rabbit hole for time so hitting the bits I *know* I can do in time first ;-)

**Pull request closed without merging**
