### PR TITLE
Added archlinux support

### PR DESCRIPTION
**Pull request by zfjagann**
1. Added a systemd package list for arch, so the packages can be managed by this cookbook, instead of failing.
1. Added attributes `node['fb_systemd']['networkd']['ignore']` and `node['fb_systemd']['resolved']['ignore']` to prevent this cookbook from taking any action on the networkd/resolved resources. [Example of this in action](https://gist.github.com/zfjagann/507e3b48a78350e716119e962b496292)

### CODE REVIEW

**Comment by jaymzh** [comment]
Unfortuantely, this violates the approach and model of Facebook's core cookbooks. The arch support is welcome, but we explicitly don't ignore stuff - our cookbooks own an entire system or leave it alone. What other configuration knobs would you need to just manage that from Chef?

**Comment by zfjagann** [comment]
Then provide a knob to disable this recipe (which I think is difficult to do). It's annoying to have the cookbook either enable the recipes, or disable them, with no option to just leave them as-is.

**Comment by davide125** [comment]
Why do you want to leave resolved/networkd unmanaged? As @jaymzh said the general philosophy is for a cookbook to manage everything; if the current API for resolved/networkd doesn't work for your usecase we should fix that, rather than adding knobs to skip parts of the recipe.

**Comment by davide125** [comment]
I'm going to close this as it's been inactive for almost two years.

**Pull request closed without merging**
